/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conferencing;

import javax.swing.JOptionPane;

/**
 *
 * @author Ashutosh
 */
public class Conference_Panel extends javax.swing.JPanel {

	/**
	 * Creates new form Conference_Panel
	 */
	public Conference_Panel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        send_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat_text_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        conf_text_area = new javax.swing.JTextArea();
        conf_name_label = new javax.swing.JLabel();
        exit_btn = new javax.swing.JButton();
        audio_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        peer_list = new javax.swing.JList();

        setPreferredSize(new java.awt.Dimension(463, 380));

        send_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conferencing/send_icon.png"))); // NOI18N
        send_btn.setToolTipText("Send");

        chat_text_area.setColumns(20);
        chat_text_area.setFont(DC_UI.ui_font);
        chat_text_area.setLineWrap(true);
        chat_text_area.setRows(5);
        chat_text_area.setToolTipText("Enter text to send");
        chat_text_area.setWrapStyleWord(true);
        jScrollPane1.setViewportView(chat_text_area);

        conf_text_area.setEditable(false);
        conf_text_area.setColumns(20);
        conf_text_area.setFont(DC_UI.ui_font);
        conf_text_area.setLineWrap(true);
        conf_text_area.setRows(5);
        conf_text_area.setWrapStyleWord(true);
        conf_text_area.setFocusable(false);
        jScrollPane2.setViewportView(conf_text_area);

        conf_name_label.setFont(DC_UI.ui_font);
        conf_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conf_name_label.setText("Conference Name");

        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conferencing/exit_icon.png"))); // NOI18N
        exit_btn.setToolTipText("Exit Conference");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        audio_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conferencing/mic_icon.png"))); // NOI18N
        audio_btn.setToolTipText("Send Audio");

        peer_list.setFont(DC_UI.ui_font);
        peer_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Users" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        peer_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(peer_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conf_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(send_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exit_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(audio_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(audio_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(send_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conf_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                        .addGap(76, 76, 76)))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents


	private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {
		// We need to kill this conference from the GUI with asking first
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton audio_btn;
    public javax.swing.JTextArea chat_text_area;
    public javax.swing.JLabel conf_name_label;
    public javax.swing.JTextArea conf_text_area;
    public javax.swing.JButton exit_btn;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JList peer_list;
    public javax.swing.JButton send_btn;
    // End of variables declaration//GEN-END:variables
}
	